project:
  type: website
  output-dir: _site

website:
  page-footer:
    left: "© 2026 Badger BioData Initiative. Code: MIT · Content: CC BY 4.0"
    center: " "
    right: 
      - icon: github
        href: https://github.com/JaydenJMerrick/biodata-ecosystem.git 
  description: "The Badger Biodata Initiative works to create a space for undergraduates to learn, create, and work with biological data."
  sidebar:
    logo: images/Badger-Biodata-Logo.png
    id: "ecosystem-sidebar"
    style: "docked"        # Keeps the vertical sidebar locked to the left side
    position: "left"       # Standard vertical alignment
    contents:
      - href: index.md
        text: "Home Page"
      - href: about-bbdi/index.md
        text: "About BDI"
      - href: member-projects/index.md
        text: "Member Projects"
      - href: club-highlights/index.md
        text: "Club Highlights"
      - href: meeting-info/index.md
        text: "Club Meeting Info"
      - href: club-events/index.md
        text: "Club Events"


format:
  html:
    theme:
        - none
        - styles.scss